#!/usr/bin/env bun
/**
 * Build script — emits the three artifact families from one token source:
 *
 *   dist/css/tokens.css        — Tailwind v4 @theme block + raw custom properties
 *   dist/tailwind/preset.{ts,js,d.ts}
 *                              — Tailwind v4 reads tokens from the CSS @theme
 *                                block, so this preset re-exports the CSS path
 *                                and the token tree for tooling that introspects
 *   dist/ts/index.{js,d.ts}    — typed const exports (compiled by tsc)
 *
 * The TS compile is driven by `bun run build` → this script → spawn `tsc`.
 */

import { spawnSync } from "node:child_process";
import { existsSync, mkdirSync, rmSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { breakpoint, color, fontSize, motion, pageWidth, radius, spacing, z } from "./src/tokens";

const ROOT = resolve(import.meta.dir ?? __dirname);
const DIST = join(ROOT, "dist");

function fresh(dir: string) {
  if (existsSync(dir)) rmSync(dir, { recursive: true });
  mkdirSync(dir, { recursive: true });
}

fresh(join(DIST, "css"));
fresh(join(DIST, "tailwind"));
fresh(join(DIST, "ts"));

// ─────────────────────────────────────────────────────────────────────────────
// 1. tokens.css — Tailwind v4 @theme block + global :root vars
// ─────────────────────────────────────────────────────────────────────────────

const css: string[] = [];
css.push("/* Auto-generated by packages/tokens/build.ts — do not edit. */");
css.push("");
css.push("@theme {");

// spacing — Tailwind v4 reads --spacing-N
for (const [k, v] of Object.entries(spacing)) {
  css.push(`  --spacing-${k}: ${v};`);
}

// fontSize — Tailwind v4 reads --text-NAME, plus --text-NAME--line-height, etc.
for (const [name, val] of Object.entries(fontSize)) {
  const [size, extra] = val as [string, Record<string, string>];
  css.push(`  --text-${name}: ${size};`);
  if (extra.lineHeight) css.push(`  --text-${name}--line-height: ${extra.lineHeight};`);
  if (extra.letterSpacing) css.push(`  --text-${name}--letter-spacing: ${extra.letterSpacing};`);
}

// color — Tailwind v4 reads --color-NAME
function emitColors(prefix: string, obj: Record<string, string>) {
  for (const [k, v] of Object.entries(obj)) {
    css.push(`  --color-${prefix}-${k}: ${v};`);
  }
}
emitColors("surface", color.surface);
emitColors("border", color.border);
emitColors("text", color.text);
emitColors("accent", color.accent);
emitColors("state", color.state);

// radius
for (const [k, v] of Object.entries(radius)) {
  css.push(`  --radius-${k}: ${v};`);
}

// breakpoints
for (const [k, v] of Object.entries(breakpoint)) {
  css.push(`  --breakpoint-${k}: ${v};`);
}

css.push("}");
css.push("");

// :root for non-Tailwind tokens (motion, z, pageWidth)
css.push(":root {");
for (const [k, v] of Object.entries(motion.duration)) {
  css.push(`  --motion-duration-${k}: ${v};`);
}
for (const [k, v] of Object.entries(motion.easing)) {
  css.push(`  --motion-easing-${k}: ${v};`);
}
for (const [k, v] of Object.entries(z)) {
  css.push(`  --z-${k}: ${v};`);
}
for (const [k, v] of Object.entries(pageWidth)) {
  css.push(`  --page-width-${k}: ${v};`);
}
css.push("}");
css.push("");

writeFileSync(join(DIST, "css", "tokens.css"), css.join("\n"));

// ─────────────────────────────────────────────────────────────────────────────
// 2. tailwind preset — Tailwind v4 reads tokens from the CSS @theme block. This
//    file exposes a JS-form preset for tools that introspect, re-exports the CSS
//    path, and re-exports the token tree from the TS build.
// ─────────────────────────────────────────────────────────────────────────────

const preset = `// Auto-generated by packages/tokens/build.ts — do not edit.
//
// Tailwind v4 reads design tokens from the \`@theme\` block in CSS, not from a JS
// preset. This file exists so consumers can do:
//
//   import { tokensCss } from "@rare-structure-hq/tokens/tailwind";
//   // tokensCss is the resolved path to the generated CSS file.
//
// It also exports the token tree (re-exported from the TS build) so non-Tailwind
// tooling (Storybook docs, tests) can pull values programmatically.

import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));

/** Absolute path to the generated tokens.css. */
export const tokensCss: string = resolve(here, "..", "css", "tokens.css");

export { tokens } from "../ts/index.js";
export type { Tokens } from "../ts/index.js";

export default { tokensCss };
`;
writeFileSync(join(DIST, "tailwind", "preset.ts"), preset);

const presetJs = `// Auto-generated by packages/tokens/build.ts — do not edit.
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
const here = dirname(fileURLToPath(import.meta.url));
export const tokensCss = resolve(here, "..", "css", "tokens.css");
export { tokens } from "../ts/index.js";
export default { tokensCss };
`;
writeFileSync(join(DIST, "tailwind", "preset.js"), presetJs);

const presetDts = `export declare const tokensCss: string;
export { tokens } from "../ts/index.js";
export type { Tokens } from "../ts/index.js";
declare const _default: { tokensCss: string };
export default _default;
`;
writeFileSync(join(DIST, "tailwind", "preset.d.ts"), presetDts);

// ─────────────────────────────────────────────────────────────────────────────
// 3. dist/ts/index.{js,d.ts} — compile src/ via tsc
// ─────────────────────────────────────────────────────────────────────────────

const tsc = spawnSync("bun", ["x", "tsc", "-p", "."], {
  cwd: ROOT,
  stdio: "inherit",
});
if (tsc.status !== 0) {
  console.error("tsc failed");
  process.exit(tsc.status ?? 1);
}

console.log("✓ tokens build complete");
console.log("  ✓ dist/css/tokens.css");
console.log("  ✓ dist/tailwind/preset.{ts,js,d.ts}");
console.log("  ✓ dist/ts/index.{js,d.ts}");
